### ISSUE TITLE
button-panelの追加機能

### ISSUE THREAD

**Issue by reiri** [OIC-Odin/smart-remote#22]
## 説明

**レビューに必要人数：2人**
**ブランチ名：** `feature/22-add-button-panel`

Myページからメニューボタンを押して、button-panelの追加ボタンを押すことで機能にアクセスできる。

`ButtonList`のレイアウトを追加。
`MyPage`に二つステートを追加：`editMode`と`buttonSize`。

`ButtonList`は`ButtonLibrary`のコレクションから完全なボタンのリストを引っ張ってきて、UIで表示する。
`ButtonList`からボタンを選択したらそのボタンの`buttonId`を`MyPage`にプロップとして渡して、`MyPage`に移動してMyPageの`editMode`を`trueにする`。
`MyPage`はボタンの種類によって`buttonSize`のステートを`small`(button panel)か `large`(RC widget)にセットする。

`PanelGroup`というコンポーネントを作って、`allSlotsEmpty`のステートを追加。
`PanelSlot`というコンポーネントを作って、`buttonId`のステートを追加。

追加するボタンのサイズは`small`だったら、全部`_id`を持ってないPanelSlot`のアイコンを "＋" のアイコンに変えて、クリックしたら、`buttonId`をセットする。変更をDBに保存。`editMode`を`false`にする。
追加するボタンのサイズは`large`だったら、全部`allSlotsEmpty`になっている`PanelGroup`のアイコンを"+
"に変えて、全部所属している`PanelSlot`に`buttonId`をセットする。変更をDBに保存。`editMode`を`false`にする。

**データベースの設計**
`Layout`のコレクション
```
{
    "_id" : ObjectId("585205d9d45f5976402d2198"),
    "userId" : "user ID",
    "myPage" : [ 
        {
            "buttonId" : "1234",
            "buttonLocation" : [ 
                1, 
                2, 
                5, 
                6
            ]
        }
    ]
}
```

## 画像
*ステートの状態*
![img_0864](https://cloud.githubusercontent.com/assets/10124806/20993513/2578c3ac-bd2e-11e6-8958-2e2a28bad998.JPG)
*Button sizeが smallの場合*
![screen shot 2016-12-08 at 11 05 14](https://cloud.githubusercontent.com/assets/10124806/20994843/5a640d30-bd36-11e6-8770-70858af19ef7.png)

*Button sizeが large の場合*
![screen shot 2016-12-08 at 11 05 30](https://cloud.githubusercontent.com/assets/10124806/20994860/7b4fdb50-bd36-11e6-9aa2-08e1b208abd0.png)

*Buttonlibrary DB specification*
![c1d51556-be24-11e6-9ab5-208410bd4eee](https://cloud.githubusercontent.com/assets/10124806/21208239/3e619628-c2b0-11e6-9903-21d5dcfdd4f7.jpg)

![slack for ios upload](https://cloud.githubusercontent.com/assets/13462428/21078816/da470f30-bfbf-11e6-8667-012a01735764.jpg)

## タスク
- [x] `ButtonList`のレイアウトを追加。
- [x] `ButtonLibrary`のコレクションから`ButtonList`にボタン情報を入れる
- [x] `MyPage`に二つステートを追加：`editMode`と`buttonSize`
- [x]  `MyPage`の動作を説明通りにする
- [x] `PanelGroup.jsx`を追加する
- [x] `PanelSlot.jsx`を追加する
- [ ] MyPageにbooleanであるの`buttonPlacement`のステートを追加する
- [x] メニューボタンを押すとbutton-panelの追加ボタンが表示される
- [ ] button-panelの選択ができる
- [ ] Myページに選択されたbutton-panelが追加される

## テスト
End to end
- [ ] ユーザーが追加したいボタンを選択して配置する
- [ ] ユーザーが追加したいボタンを空いてないスロットには入れれない。

**Comment by youmjww** [comment]
![buttonlibrary_db_specification_720](https://cloud.githubusercontent.com/assets/13462428/21039902/ae90350c-be24-11e6-81cd-c925c5369fcf.jpg)
