### ISSUE TITLE
アプリをサーバーで載せる

### ISSUE THREAD

**Issue by Dimda** [OIC-Odin/smart-remote#27]
## 説明
桜サーバーで今のアプリを載せて、公開する。
データベースをMLabに乗せる。

## 参考資料
https://www.phusionpassenger.com/library/install/apache/install/oss/xenial/
https://www.phusionpassenger.com/library/walkthroughs/deploy/meteor/ownserver/apache/oss/trusty/deploy_app.html
https://mlab.com/

## タスク
- [x] 環境変数をサーバーでセットする
- [x] アプリはサーバーで動いてる
- [x] MongoDBをMLabで動かす
- [x] ドメイン名として`smart-remote.tech`を使う

**Comment by Dimda** [comment]
今テストして二つの問題を見つけた。
1.  コンソールで`Uncaught SyntaxError: Unexpected token <`が出てる。
2. メール送信の時 http://smart-remote.tech/enroll-account/... というリンクは届いてて、http://www.smart-remote-tech にリダイレクトせれている。(DNS設定の問題？)

二つともあとでバッグカードにしていい程度だと思うから許可する。

**Comment by youmjww** [comment]
うちらのサイトは"http://smart-remote.tech/"ではなく”http://www.smart-remote.tech/”です！
もう一人の方がレビューされましたら完成へ追加お願い致します。

**Comment by gucchii** [comment]
メール送信、ユーザー情報の登録、正常に動きました。
