### ISSUE TITLE
ログイン前のページを移動する時に洗濯された言語がリセットされる

### ISSUE THREAD

**Issue by Dimda** [OIC-Odin/smart-remote#62]
## 説明

**レビューに必要人数：1人**
**ブランチ名：** `fix/62-language-is-reset-on-page-change-prior-to-login`

ログイン前のページを移動する時に洗濯された言語をURLパラメーターとして渡す。

## タスク
- [ ] Routes.js に `register` と `enroll-account` のルートに`language`というパラメーターを追加。
- [ ] `Top.jsx`の`handleSubmit`で現在の言語を`location.href`に含める
- [ ] `SignIn.jsx`の`reset-password`へのリンクで現在の言語を含める
- [ ] `SignIn.jsx`の`register`へのリンクで現在の言語を含める
- [ ] `sign-in`ページでパラメーターがあれば言語をそれに合わせてセットする
- [ ] `enroll-account`ページでパラメーターがあれば言語をそれに合わせてセットする
- [ ] `reset-password`ページでパラメーターがあれば言語をそれに合わせてセットする
- [ ] `register`ページでパラメーターがあれば言語をそれに合わせてセットする

**Comment by gucchii** [comment]
react-routerのLinkに変更した際に解決されてたみたいです。
